### ISSUE TITLE
production code not minified

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/txwrapper#3]
currently we use `tsc --build tsconfig.json` to build production code, and TS [doesn't support minification](https://github.com/microsoft/TypeScript/issues/8) out of box. 

We can pipe TS-compiled code to other minification tools to make bundle as small as possible.

**Comment by Randagio13** [comment]
Hi guys!

I think it could help you https://github.com/microsoft/TypeScript/issues/8#issuecomment-966561918
